/**
 * Words used to build team codes.
 *
 * Chosen so a captain can read one down the phone to three people standing on a
 * tee box and have them all type it correctly:
 *
 *   - 4–8 letters, one obvious spelling, no hyphens or apostrophes
 *   - no homophones or near-homophones within the list (no FLOUR/FLOWER,
 *     no BIRCH beside BIRD), because the whole point is being said out loud
 *   - concrete nouns only — nature, golf and materials. Nothing that could pair
 *     into something crude or unfortunate, since pairs are drawn at random
 *   - no I/O/L-heavy lookalikes standing alone, which is what made the old
 *     random-character codes so easy to mistype
 *
 * Exactly 128 entries. The count is not load-bearing — codes are generated by
 * rejection sampling, which is unbiased for any list length — but keeping it a
 * round power of two makes the entropy arithmetic in `generateAccessCode`
 * easy to check.
 */
export const CODE_WORDS: readonly string[] = [
  "ACORN", "ALDER", "AMBER", "ANCHOR", "APPLE", "ARBOR", "ARROW", "ASPEN",
  "BADGER", "BAKER", "BASIL", "BEACON", "BIRCH", "BIRDIE", "BISON", "BLADE",
  "BLOOM", "BRAVO", "BREEZE", "BRIDGE", "BRONZE", "BROOK", "BUNKER", "CABIN",
  "CANOE", "CANYON", "CARBON", "CEDAR", "CHALK", "CHERRY", "CIDER", "CLIFF",
  "CLOVER", "COBALT", "COMET", "CORAL", "COTTAGE", "CRANE", "CREEK", "CROWN",
  "CYPRESS", "DAISY", "DELTA", "DENIM", "DIVOT", "DRIVER", "DUNE", "EAGLE",
  "EMBER", "FALCON", "FERN", "FINCH", "FLINT", "FOREST", "FOXTAIL", "GARNET",
  "GLACIER", "GRANITE", "GRAVEL", "GROVE", "HARBOR", "HAWK", "HAZEL", "HEATHER",
  "HICKORY", "HOLLY", "HONEY", "HORIZON", "INDIGO", "IRIS", "IVORY", "JASPER",
  "JUNIPER", "KESTREL", "LANTERN", "LAUREL", "LEDGE", "LILAC", "LINDEN", "LOTUS",
  "MAGNET", "MAPLE", "MARBLE", "MEADOW", "MESA", "MILLET", "MOSS", "NECTAR",
  "NUTMEG", "OAKWOOD", "OLIVE", "ONYX", "ORCHARD", "OSPREY", "OTTER", "PEBBLE",
  "PELICAN", "PEPPER", "PINE", "PLOVER", "POPLAR", "PRAIRIE", "QUARTZ", "QUILL",
  "RAVEN", "RIDGE", "RIVER", "ROBIN", "RUSTIC", "SABLE", "SAFFRON", "SAGE",
  "SANDBAR", "SEQUOIA", "SHALE", "SIENNA", "SILVER", "SLATE", "SORREL", "SPRUCE",
  "STONE", "SUMMIT", "SWALLOW", "TALON", "TIMBER", "TOPAZ", "TULIP", "TUNDRA",
];
